In [1]:
import torch

In [2]:
x = torch.rand(3,2)

In [3]:
x

tensor([[0.9317, 0.2443],
        [0.0656, 0.4261],
        [0.3652, 0.0950]])

In [4]:
w = x @ x.T  # (3,3)
print(w)

tensor([[0.9277, 0.1652, 0.3635],
        [0.1652, 0.1859, 0.0644],
        [0.3635, 0.0644, 0.1424]])


In [5]:
alpha = torch.softmax(x, dim=1)
print(alpha)

tensor([[0.6654, 0.3346],
        [0.4108, 0.5892],
        [0.5672, 0.4328]])
