In [1]:
import torch

# Create two tensors of shape (3, 4)
a = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

b = torch.tensor([[13, 14, 15, 16],
                  [17, 18, 19, 20],
                  [21, 22, 23, 24]])

print("Tensor a shape:", a.shape)
print("Tensor b shape:", b.shape)
print("\nTensor a:\n", a)
print("\nTensor b:\n", b)

Tensor a shape: torch.Size([3, 4])
Tensor b shape: torch.Size([3, 4])

Tensor a:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Tensor b:
 tensor([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])


In [2]:
# STACK - creates a NEW dimension
stacked = torch.stack([a, b], dim=0)
print("Stacked along dim=0:")
print("Shape:", stacked.shape)
print(stacked)

Stacked along dim=0:
Shape: torch.Size([2, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


In [3]:
stacked.shape

torch.Size([2, 3, 4])

In [4]:
# CAT along dimension 0 (rows)
cat_dim0 = torch.cat([a, b], dim=0)
print("Concatenated along dim=0:")
print("Shape:", cat_dim0.shape)
print(cat_dim0)
print(cat_dim0.shape)

Concatenated along dim=0:
Shape: torch.Size([6, 4])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])
torch.Size([6, 4])


In [5]:
# CAT along dimension 1 (columns)
cat_dim1 = torch.cat([a, b], dim=1)
print("Concatenated along dim=1:")
print("Shape:", cat_dim1.shape)
print(cat_dim1)
print(cat_dim1.shape)

Concatenated along dim=1:
Shape: torch.Size([3, 8])
tensor([[ 1,  2,  3,  4, 13, 14, 15, 16],
        [ 5,  6,  7,  8, 17, 18, 19, 20],
        [ 9, 10, 11, 12, 21, 22, 23, 24]])
torch.Size([3, 8])
