In [1]:
import torch
x = torch.tensor([1,2,3,4])

In [3]:
x[:-1]

tensor([1, 2, 3])

In [1]:
print("hello world")

hello world


In [2]:
import torch

# Create a 2D tensor
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
print("Original 2D tensor:")
print(x)
print("Shape:", x.shape)

/home/abgoswam/miniconda3/envs/pytorch_gpu_1001/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


Original 2D tensor:
tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
Shape: torch.Size([3, 3])


In [10]:
x[0, 0]

tensor(10)

In [13]:
x[0:2]

tensor([[10, 20, 30],
        [40, 50, 60]])

In [17]:
x[-1:]

tensor([[70, 80, 90]])

In [18]:
x

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [20]:
x[:2]

tensor([[10, 20, 30],
        [40, 50, 60]])

In [21]:
print(x[:, ::2])

tensor([[10, 30],
        [40, 60],
        [70, 90]])


In [22]:
embeddings = torch.randn(8, 512, 768) 

In [23]:
embeddings[:3].shape # (3, 512, 768)

torch.Size([3, 512, 768])

In [25]:
embeddings[:, -1, :].shape

torch.Size([8, 768])

In [26]:
x = torch.randn(2, 3, 4, 5, 6) 

In [27]:
x[0, :, :, :, :].shape

torch.Size([3, 4, 5, 6])

In [28]:
x[0, ...].shape

torch.Size([3, 4, 5, 6])

In [29]:
x

tensor([[[[[-3.2785e-01,  5.1781e-01,  2.8241e-01, -1.3266e-01, -1.3346e+00,
            -2.0177e-01],
           [-2.7066e-01, -6.3817e-01, -5.5893e-01, -4.1947e-01, -2.9759e-01,
            -5.3273e-01],
           [ 8.4259e-01, -6.4714e-01, -1.1477e+00, -5.3388e-01, -1.4062e-01,
            -2.5239e-02],
           [-3.7582e-01, -8.2038e-01,  6.5584e-01, -1.0824e-01,  1.1327e+00,
            -7.6547e-01],
           [ 4.0936e-02, -6.2382e-01,  2.0910e-01, -4.7988e-01, -1.5397e+00,
            -3.2618e-01]],

          [[ 3.1405e+00, -5.4642e-01,  8.0515e-01, -6.2005e-01, -2.0750e-01,
            -1.5804e+00],
           [ 8.4110e-01, -2.0731e-01, -1.6525e-01,  8.4618e-01, -5.5077e-01,
            -6.8495e-01],
           [ 1.8138e-01,  7.0021e-01,  2.6484e+00, -5.9322e-01, -5.5145e-01,
            -4.6828e-02],
           [-4.0100e-02, -1.7895e-01,  1.2579e+00,  8.7750e-01,  4.0610e-01,
            -8.0084e-01],
           [ 1.8493e+00, -4.6414e-01,  6.9606e-01,  1.2536e+00, -7.2296

In [57]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

In [58]:
x = x.unsqueeze(0)

In [59]:
x.shape

torch.Size([1, 3, 3])

In [60]:
x[:, -2].shape

torch.Size([1, 3])

In [62]:
x[:, -2]

tensor([[40, 50, 60]])

In [35]:
x[..., -1]

tensor([30, 60, 90])

In [63]:
x = torch.randn(2, 3, 4)

In [64]:
x

tensor([[[ 0.0666, -2.0969,  0.9025,  1.1859],
         [ 0.7184, -0.2148, -0.5883,  0.9734],
         [ 0.9964,  1.1033, -0.1609,  2.2356]],

        [[-0.4185,  0.4464,  1.1754,  0.0034],
         [ 1.2931,  0.1067,  0.2231, -0.7307],
         [-0.2163, -0.4280,  1.3856,  0.9186]]])

In [67]:
x[..., -1]

tensor([[ 1.1859,  0.9734,  2.2356],
        [ 0.0034, -0.7307,  0.9186]])

In [68]:
x = torch.tensor([[1, -2, 3], 
                  [-4, 5, -6], 
                  [7, -8, 9]])

In [69]:
x > 0

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [70]:
x[x>0]

tensor([1, 3, 5, 7, 9])