In [ ]:
#   >>> m = nn.ReLU()
#   >>> input = torch.randn(2)
#   >>> output = m(input)


# An implementation of CReLU - https://arxiv.org/abs/1603.05201

#   >>> m = nn.ReLU()
#   >>> input = torch.randn(2).unsqueeze(0)
#   >>> output = torch.cat((m(input), m(-input)))

In [1]:
import torch
import torch.nn as nn

In [2]:
m = nn.ReLU()

In [3]:
input = torch.randn(2).unsqueeze(0)

print(input)
print(input.shape)

tensor([[-0.7479, -1.5748]])
torch.Size([1, 2])


In [4]:
print(m(input))
print(m(-input))

tensor([[0., 0.]])
tensor([[0.7479, 1.5748]])


In [5]:
output = torch.cat((m(input), m(-input)))
print(output)

tensor([[0.0000, 0.0000],
        [0.7479, 1.5748]])


In [7]:
output2 = torch.cat((m(input), m(-input)), dim=0)
print(output2)

tensor([[0.0000, 0.0000],
        [0.7479, 1.5748]])


In [8]:
torch.cuda.is_available()

True