In [4]:
import torch

In [5]:
# Level 1: Basic tensor shapes
x = torch.randn(3, 4, 5)
print(f"Tensor x shape: {x.shape}")
print(f"Number of dimensions: {x.ndim}")
print(f"Tensor:\n{x}")

Tensor x shape: torch.Size([3, 4, 5])
Number of dimensions: 3
Tensor:
tensor([[[ 0.5232, -2.1113, -0.5186, -0.2311, -1.6841],
         [ 1.0001,  0.3521, -0.5686, -0.5597, -2.0071],
         [ 0.0592, -0.2640,  0.5084,  2.5350,  1.0036],
         [ 0.4559, -0.2518,  1.4275, -0.4301, -0.1665]],

        [[-1.3089, -0.2547,  0.1019, -0.6781,  0.1971],
         [-1.1823, -0.7915,  0.1020,  0.7445, -1.8998],
         [-0.9673,  0.5342,  0.4726,  0.6367,  0.8998],
         [-0.5127, -1.1764, -0.4976, -0.4456,  1.0965]],

        [[ 0.8864, -1.5136,  0.2748, -0.1959, -0.3115],
         [-0.6263, -0.8210,  1.1989,  1.2204,  1.1547],
         [ 0.3695, -0.7759,  0.5628,  1.7819,  0.6603],
         [ 0.1412, -1.1295,  0.5960, -0.2404, -0.9638]]])


In [11]:
# You can also use negative indices
x_unsqueeze_neg1 = x.unsqueeze(-1)
print(f"After unsqueeze(-1): {x_unsqueeze_neg1.shape}")
# print(f"Tensor:\n{x_unsqueeze_neg1}")

# You can also use negative indices
x_unsqueeze_neg2 = x[..., None]
print(f"After unsqueeze(-1): {x_unsqueeze_neg2.shape}")
# print(f"Tensor:\n{x_unsqueeze_neg2}")

After unsqueeze(-1): torch.Size([3, 4, 5, 1])
After unsqueeze(-1): torch.Size([3, 4, 5, 1])


In [14]:
x_unsqueeze_neg2

tensor([[[[ 0.5232],
          [-2.1113],
          [-0.5186],
          [-0.2311],
          [-1.6841]],

         [[ 1.0001],
          [ 0.3521],
          [-0.5686],
          [-0.5597],
          [-2.0071]],

         [[ 0.0592],
          [-0.2640],
          [ 0.5084],
          [ 2.5350],
          [ 1.0036]],

         [[ 0.4559],
          [-0.2518],
          [ 1.4275],
          [-0.4301],
          [-0.1665]]],


        [[[-1.3089],
          [-0.2547],
          [ 0.1019],
          [-0.6781],
          [ 0.1971]],

         [[-1.1823],
          [-0.7915],
          [ 0.1020],
          [ 0.7445],
          [-1.8998]],

         [[-0.9673],
          [ 0.5342],
          [ 0.4726],
          [ 0.6367],
          [ 0.8998]],

         [[-0.5127],
          [-1.1764],
          [-0.4976],
          [-0.4456],
          [ 1.0965]]],


        [[[ 0.8864],
          [-1.5136],
          [ 0.2748],
          [-0.1959],
          [-0.3115]],

         [[-0.6263],
          [-

In [12]:
x_unsqueeze_3 = x[None, ...]
x_unsqueeze_3.shape

torch.Size([1, 3, 4, 5])

In [13]:
x_unsqueeze_3

tensor([[[[ 0.5232, -2.1113, -0.5186, -0.2311, -1.6841],
          [ 1.0001,  0.3521, -0.5686, -0.5597, -2.0071],
          [ 0.0592, -0.2640,  0.5084,  2.5350,  1.0036],
          [ 0.4559, -0.2518,  1.4275, -0.4301, -0.1665]],

         [[-1.3089, -0.2547,  0.1019, -0.6781,  0.1971],
          [-1.1823, -0.7915,  0.1020,  0.7445, -1.8998],
          [-0.9673,  0.5342,  0.4726,  0.6367,  0.8998],
          [-0.5127, -1.1764, -0.4976, -0.4456,  1.0965]],

         [[ 0.8864, -1.5136,  0.2748, -0.1959, -0.3115],
          [-0.6263, -0.8210,  1.1989,  1.2204,  1.1547],
          [ 0.3695, -0.7759,  0.5628,  1.7819,  0.6603],
          [ 0.1412, -1.1295,  0.5960, -0.2404, -0.9638]]]])