In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

import helper_utils

# This line ensures that your results are reproducible and consistent every time.
torch.manual_seed(42)

In [2]:
# Distances in miles for recent bike deliveries
distances = torch.tensor([[1.0], [2.0], [3.0], [4.0]], dtype=torch.float32)

# Corresponding delivery times in minutes
times = torch.tensor([[6.96], [12.11], [16.77], [22.21]], dtype=torch.float32)

In [3]:
distances.shape

torch.Size([4, 1])

In [4]:
model = nn.Sequential(nn.Linear(1, 1))

In [7]:
print(model)
print(model[0])

Sequential(
  (0): Linear(in_features=1, out_features=1, bias=True)
)
Linear(in_features=1, out_features=1, bias=True)


In [11]:
pl = list(model.parameters())

In [15]:
print(pl[0])

Parameter containing:
tensor([[0.7645]], requires_grad=True)


In [16]:
for name, param in model.named_parameters():
    print(f"  {name}: shape {param.shape}, requires_grad={param.requires_grad}")


  0.weight: shape torch.Size([1, 1]), requires_grad=True
  0.bias: shape torch.Size([1]), requires_grad=True


In [30]:
print(pl[1].data)  # weight values without the "Parameter containing" wrapper
print(pl[1].shape)  # shape of the weight

tensor([0.8300])
torch.Size([1])


In [18]:
# See just the weight tensor
print(pl[0])  # weight parameter

# See just the bias tensor  
print(pl[1])  # bias parameter

Parameter containing:
tensor([[0.7645]], requires_grad=True)
Parameter containing:
tensor([0.8300], requires_grad=True)


In [33]:
model[0]

Linear(in_features=1, out_features=1, bias=True)

In [34]:
model[0].weight

Parameter containing:
tensor([[0.7645]], requires_grad=True)

In [35]:
model[0].bias

Parameter containing:
tensor([0.8300], requires_grad=True)