In [1]:
import torch

In [2]:
input_dim = 4
hidden_dim = 8
num_gpus = 4

In [3]:
W1 = torch.randn(input_dim, hidden_dim)
print(W1.shape)

W1_flat = W1.flatten()
print(W1_flat.shape)

torch.Size([4, 8])
torch.Size([32])


In [6]:
print(W1)

tensor([[ 0.4210, -1.7045,  0.1396,  0.1516,  0.8668,  1.3000, -1.2300,  1.0477],
        [ 0.4492, -0.2479,  0.3656,  0.3685,  0.7257,  0.9911, -0.7914,  0.9561],
        [-0.3582, -0.2027,  0.7610, -0.4558, -0.3629,  1.4698,  0.5466, -1.0819],
        [ 0.6343,  0.5319, -0.6258, -1.7105, -1.0331,  0.2972,  1.4856,  1.4777]])


In [4]:
W1_fsdp_shards = torch.chunk(W1_flat, num_gpus)

In [5]:
W1_fsdp_shards

(tensor([ 0.4210, -1.7045,  0.1396,  0.1516,  0.8668,  1.3000, -1.2300,  1.0477]),
 tensor([ 0.4492, -0.2479,  0.3656,  0.3685,  0.7257,  0.9911, -0.7914,  0.9561]),
 tensor([-0.3582, -0.2027,  0.7610, -0.4558, -0.3629,  1.4698,  0.5466, -1.0819]),
 tensor([ 0.6343,  0.5319, -0.6258, -1.7105, -1.0331,  0.2972,  1.4856,  1.4777]))

In [8]:
torch.cat(W1_fsdp_shards).shape

torch.Size([32])

In [13]:
a = torch.randn(2)
b = torch.randn(2)

print(a)
print(b)
print(torch.cat([a,b]))

tensor([2.5942, 0.8361])
tensor([-0.5267,  0.6743])
tensor([ 2.5942,  0.8361, -0.5267,  0.6743])
